name = "NaturalIsotopeCorrection"
uuid = "ada07ce9-609d-4543-9e41-2cdc42bc1f8f"
authors = ["Vincent M. von Häfen"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
